### ISSUE TITLE
buggy workflow when creating a new account after logging out of previous one

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#381]
just letting you know here - maybe ive missed something. i created an account 'darkbrown'. i was previously signed into the account 'olga'. when i finished the registration and logged into dark brown and compose

steps:

1.  i have olga's email address under my autocomplete.
2. she's marked as secure. i havent imported her public key yet. no prompt was shown and i sent olga an email.
3. olga receives email and was able to decrypt it. I replied from that email and it gave me a warning that I didn't have darkbrown's public key. I sent the email with some content.
4. darkbrown receives it as a blank email (subject is there but body isnt).

**Comment by let4be** [comment]
Thanks. Will check
This sort of behavior happens because we do not unload the angular application, we simply switch between primary app and sign in/up app - to avoid delays and possibly screen blinking on page reload.
Most of such clean up situations should already be handled properly, but something is not

**Comment by let4be** [comment]
related: https://github.com/lavab/web/issues/382
