### ISSUE TITLE
Login App shifted to the right

### ISSUE THREAD

**Issue by flixi** [lavab/web#402]
![bildschirmfoto 2015-04-04 um 22 37 42](https://cloud.githubusercontent.com/assets/707993/6994475/6d65c0d0-db1b-11e4-9bbd-84b515448866.png)

**Comment by piggyslasher** [comment]
@let4be im going to hide notifications in the login app man. Please show notifications within the respective jade file at the end. is there a show way of appending this to all jade files in the login folder? like a jade import?

**Comment by let4be** [comment]
jade files inside login are partials that being included via angular-ui-router
please import this inside index.jade

**Comment by let4be** [comment]
This is the place where partials are being included:
https://github.com/lavab/web/blob/develop/src/index.jade#L59-59

**Comment by piggyslasher** [comment]
yes, this i know they are separate jade files in the partials folder :) I just want to know if there's anyway of appending this to the end of all _those_ jade files programatically. i cant put anything in that index.jade div because the router will overwrite it. i tried putting notifications inside there but i guess the ui-router loads the partial jade file in there.
