### ISSUE TITLE
Lock Icon: color mix-up

### ISSUE THREAD

**Issue by vLooz** [lavab/web#447]
I've talked about the lock icon colors with @flixi and he advised me to get a straighter color pattern for the locks throughout the UI. 

We decided that...
...all closed locks (encrypted) should be blue (#3BBADDC) 
...and all open locks (not encrypted) should be light grey (#C6C6C6)

The reason for this is the assumed fact, that most users will have non-pgp contacts and therefor unencrypted mails for about 90% of the time (at least in the beginning). We don't wanna make them feel uneasy by showing them red open locks all the time. Still we want to show them what's encrypted and what is not, so they can change the latter by inviting all friends to Lavaboom ;-)

So instead of this...

![mixed up d colors](https://cloud.githubusercontent.com/assets/11177812/7089102/ad3ce490-df99-11e4-8b5c-d8290a485973.png)

...we use this now. This is true for all situations where those small locks appear (mail list view, mail previews, recipient selection etc...): 

![correct colors](https://cloud.githubusercontent.com/assets/11177812/7089730/382d55cc-df9e-11e4-9aa7-ecb760db89e5.png)
![bildschirmfoto 2015-04-10 um 16 24 08](https://cloud.githubusercontent.com/assets/11177812/7089732/3b9539be-df9e-11e4-9f7f-c721daae4e28.png)

I'm sorry for the extra work, but I think this is more consistent, and by this more user-friendly.

**Comment by piggyslasher** [comment]
all done. was a quick fix because i was fixing a lot of the other colors as well. i knew you weren't happy with some of them @vLooz 

![image](https://cloud.githubusercontent.com/assets/1991125/7253140/eaa96a8e-e86c-11e4-8099-de1ec7e31e78.png)

the icons now look like this in the dropdown though. I know it needs to be tweaked more but just wanna say that while using it it was hard to see which is secure and which is not because my ey needs to move to the end of every email. its almost tiring. maybe the icons should be shown on the left before the email?

anyway. going to mark this as done as the colors are correct.

**Comment by vLooz** [comment]
Great work@piggyslasher! 

I guess part of the tiring effect is the small distance between the lines. This way the eye connects the lock icons vertically instead of connecting them with the addresses horizontally. 

Ideas to improve:
Try to make it larger to give it more 'breathing space' 
Make the grey locks a tiny bit smaller 
Try to give the blue lock icon the exact same width like the grey lock. It will look more calm then.

**Comment by piggyslasher** [comment]
will do. i will create a new issue for those.

edit: i'll add them to #261 as that has more guidelines for the dropdown itself.
