### ISSUE TITLE
Contacts: Responsive Bugs

### ISSUE THREAD

**Issue by vLooz** [lavab/web#482]
On http://127.0.0.1:5000/contacts/profile/ZMHSv4jZObW3ACHjctEt (Viks Version) this happens, when I make the window smaller:
![contacts responsive bugs](https://cloud.githubusercontent.com/assets/11177812/7157496/7a758ad2-e370-11e4-8d67-b5475dab555e.png)

**Comment by piggyslasher** [comment]
yes. the profile picture takes full width because the fields needs to be a usable width.

Vikram Ramanujam [7:19 PM]
thats okay right?

Vikram Ramanujam [7:19 PM]
the center pane i'll fix it more.

problem is we didnt plan for anything less than 600px width yet @fvl - there was going to be a mobile interface for that.

Vikram Ramanujam [7:20 PM]
afaik, that was my instructions.

Vikram Ramanujam [7:21 PM]
maybe we should set the min width of the entire page and show a scrollbar when things get too narrow.

Vikram Ramanujam [7:22 PM]
maybe, on even smaller screens we make the left menu slightly narrower to save valuable space.

**Comment by piggyslasher** [comment]
- [ ] set min-width
  - [ ] fix mid-pane icon wrapping
