### ISSUE TITLE
Contacts / PublicKey Download better UX

### ISSUE THREAD

**Issue by vLooz** [lavab/web#503]
Actual UX
When the user is downloading a contacts public key, a new empty tab is opened and an text file with the name "unknown" is downloaded. I think this a bit confusing for the user.

Better UX:
When the user is downloading a contacts public key, no new tab is opened (a bit annoying) and the text file is named "contactname_publickey.txt"

**Comment by piggyslasher** [comment]
Yes, this was an issue with Safari only for locally generated files - and
Apple aren't going to fix it anytime soon. They have two-three very busy
bug reports on this and they don't seem to care.

This is something we simply could not fix. Because of our zero-knowledge
framework we can't send any data to the server and therefore we can't do
stuff like file renaming for locally generated files..

There is simply no way around this for Safari users sadly. Perhaps we can
warn safari users.

**Comment by piggyslasher** [comment]
Im want to add a won't fix tag because both @let4be and I tried our best to workaround this. Its different when you get files from a server - you can set the filename. But in this case, its being generated within the browser locally and then saved.

Then again - this is the __public__ key - we _can_ send it to the server and get it back as a file right? It's already public? @flixi @vLooz @andreis

**Comment by andreis** [comment]
We'll warn Safari users and later direct them to the desktop app (packaged with node-kit or atom-shell)

**Comment by andreis** [comment]
Wait, I mean *[Electron](https://github.com/atom/electron)* and *[NW.js](http://nwjs.io/)*, of course.

-.-

**Comment by piggyslasher** [comment]
I'm doing a pet project on nw.js and they still don't have proper cross-platform HTML5 notification support. going to try out atom-shell.
