### ISSUE TITLE
Login sometimes hangs at Initializing openpgp.js

### ISSUE THREAD

**Issue by flixi** [lavab/web#514]
https://gist.github.com/flixi/5b666bc4c17dc785cd5f

**Comment by mlooz** [comment]
It might be an issue with connectivity to the api server.
When using a local version of the web-framework without internet access, this bug appears always.
When using .com or a local version with internet access, it appears sometimes.

**Comment by piggyslasher** [comment]
But it shouldn't hang during initialitizing openPGP.js - we're simply loading the javascript file. unless something is failing. @mlooz  - could you please post a screenshot of the console log when this happens? Thanks.

**Comment by piggyslasher** [comment]
@mlooz - can you give me a screenshot of you console log when this happens? not much we can make out from @flixi's gist file. seems to be a toned down version of the console. It shouldn't hang on openPGP because we're just loading a javascript file at that point. local version doesn't seem to have this error.

**Comment by flixi** [comment]
I'm sorry but this is the console that is apparent in Safari.

**Comment by mlooz** [comment]
[This](https://gist.github.com/mlooz/9b547f6f96fafbd93713) is my gist of a Firefox console log. Unfortunately, it is in German, but the rough structure should be apparent. Since I couldn't recreate it in .com after several attempts, I did the following:

1. Run  local version with c62b90f3b4b60186b13afe458b8d56f3e0062a44
2. Disconnect Internet
3. Visit localhost:5000
4. Wait
5. Reconnect internet
6. Copy logs

The page hanged, showing "Initializing openPGP.js". In the log file, several unsuccessful GET-requests appeared. After I reconnected the internet connection, the page still hanged.

I'm not sure if this is the same bug as on .com, but it appears related. Maybe some timeout issue only appearing on high load?

**Comment by piggyslasher** [comment]
that is weird. how about using 127.0.0.1:5000? OpenCrypto sometimes has
problems on localhost and 0.0.0.0
change the listening address from 0.0.0.0 or localhost in
/src/gulp/config.js to 127.0.0.1 - and please let me know if you still get
this issue. much appreciated.

**Comment by mlooz** [comment]
Will try!
Don't have access to my computer right now, will test on Monday.

On 24. April 2015 04:11:59 MESZ, piggyslasher <notifications@github.com> wrote:
>that is weird. how about using 127.0.0.1:5000? OpenCrypto sometimes has
>problems on localhost and 0.0.0.0
>change the listening address from 0.0.0.0 or localhost in
>/src/gulp/config.js to 127.0.0.1 - and please let me know if you still
>get
>this issue. much appreciated.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lavab/web/issues/514#issuecomment-95774909

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by let4be** [comment]
There is a bug in initialization flow and error handling when connection is lost most likely(same with https://github.com/lavab/web/issues/513). Will fix as soon as get back

**Comment by mlooz** [comment]
Using 127.0.0.1:5000 on 34daf95b1c8c6821960e31023db1991578d13694 results in the same behaviour as posted above: Login hangs on "Initializing openpgp.js" when connection is lost, doesn't recover when connection is reestablished.

**Comment by let4be** [comment]
I'm still checking regarding connection error handling, seems like this is another cause of this error
open issue for this: https://github.com/lavab/web/issues/535

**Comment by mlooz** [comment]
Tested on local version of 733b50e77719950f9598a86ad8bb52bb127d618c, error didn't occur in the four attempts I did. Disconnecting internet during login causes the page to hang, but it recovers after reconnection.
