### ISSUE TITLE
Allow writing plain emails in the UI

### ISSUE THREAD

**Issue by pzduniak** [lavab/web#546]
Right now I have to use that WYSIWYG thingy, which is quite annoying if you want to send certs/keys etc.

**Comment by let4be** [comment]
I don't get what you want to do @pzduniak, please provide more information
You can easily send cert/keys as attachments or if they are in text format(armored) just copy-paste them, what's the problem?

**Comment by piggyslasher** [comment]
Dont think we need this to be some form of a different way of sending emails (i.e. plaintext vs html). I think we've come to a stage where an email, whatever its contents is just sent and received. If the user understands keys/certs, its up to him to copy paste it. if he does this properly (which I expect him to do so because he already knows what certs/keys are) then he's just gonna copy/paste the received email into a text file.

as @let4be said - we already allow attachments. just drag the file in.

**Comment by let4be** [comment]
After dealing with some debug/copy&&paste yesterday I now understand what @pzduniak is talking about :)
We definitely need some kind of strict mode in text-angular where no post processing will be executed except wrapping the mail into <pre> tag during display

This then should have type `text/plain` and be rendedred using simple <pre> tag without any post-processing.
