### ISSUE TITLE
Mails no longer readable

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#555]
After I logged in this morning, all my mails are marked as "encrypted thread". Instead of a text, I see

No decrypted private key found for this email
Please go to settings and check your key

If I go to "settings", my key still seems to be available.

**Comment by jrselzer** [comment]
Mails are still readable on my Android device.

**Comment by jrselzer** [comment]
Had to quit my session and to log in again to be able to read my mails.

**Comment by pzduniak** [comment]
We couldn't reproduce this issue for quite some time and then it suddenly started happening again. After cache resets, the decrypted key is not accessible and you have to manually decrypt it in settings. Password prompt should pop up in such case.

**Comment by let4be** [comment]
> If I go to "settings", my key still seems to be available
if key is here _the only_ valid reason for this behavior is key isn't decrypted(red lock icon is being displayed near the key)

to manually decrypt your key you need to click on the key header and enter your password

**Comment by pzduniak** [comment]
But it isn't clear, users can't read our minds. @vLooz ideas?

**Comment by let4be** [comment]
we clearly inform the user that he needs to 
> Please go to settings and check your key

What worries me here is how this happned... If decrypted key was in local storage the only valid reason for such behavior is manual key removal OR clicking on "Remove decrypted keys" button in the Settings/Keys

**Comment by vLooz** [comment]
In my opinion a note, thats says "please check you key" doesn't make much sense, if the user doesn't know what to do then or maybe is not able to do something at all.

I'd prefer an automated reaction of the system, instead of bothering the user. For example reload of private key into the cache via Key sync. 

a) If this is not working, there is something so wrong with the system, that the user can't do anything about it (at least I wouldn't know what I could do). So we just let the user know that there is a bug, we apologize for the inconvenience and promise her to take care of this asap etc... 

b) In case the user really manually deleted the keys and doesn't have key sync switched on, the only option is to upload the key backup, so we ask the user to do this. Ideally in a pop-up window that appears immediately, so the user doesn't have to go to settings/keys etc.

**Comment by let4be** [comment]
We never store decrypted key in key backup, so password required anyway(LS sync doesn't help to get you decrypted private key without password)

**Comment by vLooz** [comment]
But isn't everything decrypted anyways when the user is logged in?

**Comment by pzduniak** [comment]
Nope, all private keys are encrypted using the account's password.

**Comment by let4be** [comment]
There are 2 possible ways to login:
- manually enter login and password
- login via stored authentication token ("remember me" functionality)

When we login via stored authentication token we don't have user password at all

**Comment by jrselzer** [comment]
Re-login is definitely a workaround I can live with.

**Comment by vLooz** [comment]
But isn't the option to login without entering the account password part of the problem?

**Comment by let4be** [comment]
This happens automatically and part of "remember me" flow which is totally okay,
the problem is most likely lies in accidental/on purpose "remove decrypted keys" press

**Comment by vLooz** [comment]
So we need the "Expert" mode earlier than later to prevent accidental things like this.

**Comment by let4be** [comment]
Just reproduced this bug, heh
It seems to happen only after initial sign up when you don't check "This is private PC"
Keys were getting persisted in Session Storage as they should but lava token in local storage

so after page re-open user ended up with no decrypted private keys but with valid lava token :D

Will fix soon along with the new security model regarding storing && displaying private keys

**Comment by let4be** [comment]
Currently sits in custom branch, will merge today with a bunch of other related updated and improvements
