### ISSUE TITLE
Big-ass icons

### ISSUE THREAD

**Issue by andreis** [lavab/web#684]
While I agree that everything was too small before, the extra-large icons just look bad and amateur-y now, especially since the text is way smaller.

![screen shot 2015-05-14 at 23 44 25](https://cloud.githubusercontent.com/assets/1249760/7642680/523e8a16-fa93-11e4-8aee-84bc1b52e26d.png)

Please:

* reduce the size of the icons in the left panel **just slightly**
* reduce the size of the icons + captions in the middle panel (for Settings) *more*

**Comment by piggyslasher** [comment]
@vLooz

**Comment by vLooz** [comment]
I disagree with @andreis in this case. We can decrease the size if the middle icons a bit though. Do not touch the left panel icons please, it took is ages to get them to the right size. Please get the left panel icons back to the color (grey instead of white) we had before. Then they will look less heavy and intrusive @piggyslasher.

**Comment by andreis** [comment]
:+1:

**Comment by piggyslasher** [comment]
done.

**Comment by andreis** [comment]
Thank you :+1:
