### ISSUE TITLE
Hidden contacts

### ISSUE THREAD

**Issue by let4be** [lavab/web#860]
Should we show them/hide them?
What should we consider a hidden contact?
cc @andreis @vLooz @flixi

**Comment by vLooz** [comment]
From my pov I'd offer every contact, the user already has sent a mail to in the "select recipient" field. those which are not saved as contacts just in form of the email address, those which are saved as the full contact entry like it is now.

**Comment by let4be** [comment]
Don't understand this @vLooz 

>those which are not saved as contacts
what do we save as contact and what not?

I think previous model <=0.4.4 isn't so good because doesn't give user a direct possibility to remove/give a name to the hidden contact

**Comment by andreis** [comment]
A solution would be to have a `x` over the autocomplete suggestion for hidden contacts. Also, please do **not** show hidden contacts in Contacts!

**Comment by vLooz** [comment]
I think we have 3 different kind of recipient addresses:

1. an address, thats has been added to contacts manually by the user

2. an address, that has not been added to contacts by the user, but has been used to send a mail to.

3. an address, that has been typed into the recipient form, but has been deleted afterwards (maybe because there was a typo e.g.) and this for was NOT used to send an email to.

From my pov only the second kind should be saved and shown as a hidden contact, when the user types something into the recipient field.

**Comment by andreis** [comment]
@vLooz `2.` is exactly what hidden contacts are, Sergey was just arguing for giving the users the ability to delete hidden contacts, since it can be annoying to get a suggestion for a contact you've only sent an email to oncer 3 years ago.

**Comment by let4be** [comment]
well, there was another ticket and I misunderstood what we want to see.
https://github.com/lavab/web/issues/461

so I made hidden contacts look as normal contacts... i.e. appear in the global contacts list

This change is reverted in develop now
