### ISSUE TITLE
Please make the header "non-scrollable" 

### ISSUE THREAD

**Issue by vLooz** [lavab/web#917]
mail.lavaboom.io

What happens:
When I scroll up an empty folder, the header moves downwards with it, pulling itself from the upper edge of the window.

What should happen:
The Header should just always stay in position, no matter what action the user does. Exactly like the left panel.

<img width="1208" alt="bildschirmfoto 2015-07-14 um 09 36 13" src="https://cloud.githubusercontent.com/assets/11177812/8668491/fa5fc852-2a0b-11e5-9424-465c21ce801a.png">

**Comment by piggyslasher** [comment]
This happens on all websites. Check out Google Inbox below.
![image](https://cloud.githubusercontent.com/assets/1991125/8719618/a224de5e-2bdf-11e5-872a-5ac8eab0fa87.png)
The problem is with Mac. Rubberbanding as we call it is built in. There's no way to work around this. It happens in every browser except Firefox. This can be fixed with a few hacks, but this is the way Mac's work. Do you really want this to be fixed @vLooz?

**Comment by piggyslasher** [comment]
Happens on github & waffle as well :)

**Comment by vLooz** [comment]
damn... why is reality always getting in zee way wis my ideas? ;)
Leave it then.
